server:
  port: 9999
spring:
  appliction:
    name: authentication_server
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_db?useSSL=false
    username: root
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

